services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.axum
    env_file:
      - .env
    environment:
      APP__DATABASE__HOST: postgres
      APP__DATABASE__PORT: 5432
    depends_on:
      - postgres
    ports:
      - "${APP__APPLICATION_PORT}:${APP__APPLICATION_PORT}"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${APP__DATABASE__USERNAME}
      POSTGRES_PASSWORD: ${APP__DATABASE__PASSWORD}
      POSTGRES_DB: ${APP__DATABASE__DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${APP__DATABASE__PORT}:5432"
    restart: unless-stopped

volumes:
  postgres_data:
